# These are supported funding model platforms

github: [a-patel]
patreon: iamaashishpatel
open_collective: iamaashishpatel
tidelift: nuget/LiteX.Cache
custom: https://www.buymeacoffee.com/iamaashishpatel
ko_fi: # Replace with a single Ko-fi username
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
